import type { ProjectType } from '@/types/projectInfo'

const PROJECTS_LIST: ProjectType[] = [
  {
    title: 'Platipie',
    description:
      'SaaS Platform for creating, managing and developing E-commerce stores on no-code platform (Webflow).',
    categories: [
      // 'Frontend',
      // 'Backend',
      'Software Development',
      'Plugins & Extensions',
    ],
    tags: [
      'SaaS: Software-as-a-Service',
      'Vertical Platform',
      'E-Commerce',
      'Webflow App',
    ],
    website: 'platipie.com',
    github: '',
    heroImage: '',
  },
  {
    title: 'Replocal App',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Fork Watch',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Webflow Apps Design System',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Hooop Cloud',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Personal Website (v2)',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Maanas',
    description:
      'Second brain for myself featuring notes, time blocking, and a knowledge base.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Blog Platform',
    description:
      'Library for creating realtime offline-first applications with PWA, Service Workers, IndexedDB.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'SaaS: Software-as-a-Service',
      'Developer Tool',
      'Platform',
      'TypeScript',
      'MQTT',
      'SST',
      'Pulumi',
      'IaaC',
    ],
    website: 'replocal.app',
    github: '',
    heroImage: '',
  },
  {
    title: 'Vasundhara',
    description:
      'Commercial Fleet, Accounting, Compliance, Vendor, Drivers and Staff Management System.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Realtime Admin Panel',
      'GPS',
      'MQTT',
      'Government APIs',
      'External APIs',
      'Google Maps',
      'AWS',
      'DynamoDB',
    ],
    website: 'manage.vasundhara.cc',
    github: '',
    heroImage: '',
  },
  {
    title: 'Aakash',
    description:
      'AI Chatbot that uses function calling and database memory to recommend business decisions and actions.',
    categories: ['Artificial Intelligence'],
    tags: [
      'AI Chatbot',
      'LLM',
      'LangChain.js',
      'LangSmith',
      'OpenAI',
      'Mixtral',
      'Anthropic',
      'Function Calling',
    ],
    website: 'chat.vasundhara.cc',
    github: '',
    heroImage: '',
  },
  {
    title: 'DynamoDB SDK',
    description:
      'TypeScript SDK for DynamoDB to make it type-safe and easier to work with.',
    categories: [
      // 'Library',
      'Software Development',
      'Platform Engineering',
    ],
    tags: [
      'Open Source',
      'Package',
      'SDK',
      'Developer Tool',
      'Typescript',
      'AWS DynamoDB',
      'SST',
      'Schema',
    ],
    website: 'dynamodb-sdk.com',
    github: '',
    heroImage: '',
  },
  {
    title: 'Chess Coach',
    description:
      'AI platform to analyze chess matches and recommend training modules to players.',
    categories: ['Software Development', 'Artificial Intelligence'],
    tags: [
      'AI',
      'TypeScript',
      'Chess.com API',
      'LangChain.js',
      'LangSmith',
      'OpenAI',
      'Mixtral',
    ],
    website: 'chess.adityaborkar.com',
    github: '',
    heroImage: '',
  },
  {
    title: 'Amy',
    description:
      'Extension for Google Sheets to syncronize dates with Google Calendar with event customization.',
    categories: ['Plugins & Extensions'],
    tags: [
      'Google Apps Script',
      'JavaScript',
      'Google Calendar Advanced API',
      'Google Sheets API',
    ],
    website: '',
    github: '',
    heroImage: '',
  },
  {
    title: 'GeM Finder',
    description:
      'Google Chrome Extension to navigate the GeM website and get personalized bids.',
    categories: ['Software Development', 'Plugins & Extensions'],
    tags: [
      'Google Chrome Extension',
      'Web Scraping',
      'Govt. of India API',
      'Data Analysis',
      'Personalization',
    ],
    website: 'gem.vasundhara.cc',
    github: '',
    heroImage: '',
  },
]

export default PROJECTS_LIST
